//
// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
// Autogenerated from Pigeon (v26.1.10), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.amazonaws.amplify.amplify_auth_cognito

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object WebAuthnBridgePigeonPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

// FlutterError is declared in NativeAuthPluginBindingsPigeon.kt (same package).
private open class WebAuthnBridgePigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}


/**
 * Pigeon bridge for WebAuthn/passkey operations.
 *
 * Platform implementations (iOS/macOS via ASAuthorizationController,
 * Android via CredentialManager) handle the native ceremony and return
 * JSON-serialized W3C WebAuthn Level 3 response objects.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface WebAuthnBridgeApi {
  /**
   * Creates a new passkey credential on the device.
   *
   * [optionsJson] is a JSON-serialized `PublicKeyCredentialCreationOptions`.
   * Returns a JSON-serialized `RegistrationResponseJSON`.
   */
  fun createCredential(optionsJson: String, callback: (Result<String>) -> Unit)
  /**
   * Retrieves a passkey credential assertion for authentication.
   *
   * [optionsJson] is a JSON-serialized `PublicKeyCredentialRequestOptions`.
   * Returns a JSON-serialized `AuthenticationResponseJSON`.
   */
  fun getCredential(optionsJson: String, callback: (Result<String>) -> Unit)
  /** Returns whether the current device/platform supports passkeys. */
  fun isPasskeySupported(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by WebAuthnBridgeApi. */
    val codec: MessageCodec<Any?> by lazy {
      WebAuthnBridgePigeonPigeonCodec()
    }
    /** Sets up an instance of `WebAuthnBridgeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WebAuthnBridgeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amplify_auth_cognito.WebAuthnBridgeApi.createCredential$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsJsonArg = args[0] as String
            api.createCredential(optionsJsonArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WebAuthnBridgePigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WebAuthnBridgePigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amplify_auth_cognito.WebAuthnBridgeApi.getCredential$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsJsonArg = args[0] as String
            api.getCredential(optionsJsonArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WebAuthnBridgePigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WebAuthnBridgePigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amplify_auth_cognito.WebAuthnBridgeApi.isPasskeySupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isPasskeySupported{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WebAuthnBridgePigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WebAuthnBridgePigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
