//
// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
// Autogenerated from Pigeon (v26.1.10), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class WebAuthnBridgePigeonCodecReader: FlutterStandardReader {
}

private class WebAuthnBridgePigeonCodecWriter: FlutterStandardWriter {
}

private class WebAuthnBridgePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return WebAuthnBridgePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return WebAuthnBridgePigeonCodecWriter(data: data)
  }
}

class WebAuthnBridgePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = WebAuthnBridgePigeonCodec(readerWriter: WebAuthnBridgePigeonCodecReaderWriter())
}


/// Pigeon bridge for WebAuthn/passkey operations.
///
/// Platform implementations (iOS/macOS via ASAuthorizationController,
/// Android via CredentialManager) handle the native ceremony and return
/// JSON-serialized W3C WebAuthn Level 3 response objects.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WebAuthnBridgeApi {
  /// Creates a new passkey credential on the device.
  ///
  /// [optionsJson] is a JSON-serialized `PublicKeyCredentialCreationOptions`.
  /// Returns a JSON-serialized `RegistrationResponseJSON`.
  func createCredential(optionsJson: String, completion: @escaping (Result<String, Error>) -> Void)
  /// Retrieves a passkey credential assertion for authentication.
  ///
  /// [optionsJson] is a JSON-serialized `PublicKeyCredentialRequestOptions`.
  /// Returns a JSON-serialized `AuthenticationResponseJSON`.
  func getCredential(optionsJson: String, completion: @escaping (Result<String, Error>) -> Void)
  /// Returns whether the current device/platform supports passkeys.
  func isPasskeySupported(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WebAuthnBridgeApiSetup {
  static var codec: FlutterStandardMessageCodec { WebAuthnBridgePigeonCodec.shared }
  /// Sets up an instance of `WebAuthnBridgeApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WebAuthnBridgeApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Creates a new passkey credential on the device.
    ///
    /// [optionsJson] is a JSON-serialized `PublicKeyCredentialCreationOptions`.
    /// Returns a JSON-serialized `RegistrationResponseJSON`.
    let createCredentialChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amplify_auth_cognito.WebAuthnBridgeApi.createCredential\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createCredentialChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsJsonArg = args[0] as! String
        api.createCredential(optionsJson: optionsJsonArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createCredentialChannel.setMessageHandler(nil)
    }
    /// Retrieves a passkey credential assertion for authentication.
    ///
    /// [optionsJson] is a JSON-serialized `PublicKeyCredentialRequestOptions`.
    /// Returns a JSON-serialized `AuthenticationResponseJSON`.
    let getCredentialChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amplify_auth_cognito.WebAuthnBridgeApi.getCredential\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCredentialChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsJsonArg = args[0] as! String
        api.getCredential(optionsJson: optionsJsonArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCredentialChannel.setMessageHandler(nil)
    }
    /// Returns whether the current device/platform supports passkeys.
    let isPasskeySupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amplify_auth_cognito.WebAuthnBridgeApi.isPasskeySupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isPasskeySupportedChannel.setMessageHandler { _, reply in
        api.isPasskeySupported { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isPasskeySupportedChannel.setMessageHandler(nil)
    }
  }
}
