//
// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
// Autogenerated from Pigeon (v26.1.10), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}



class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Pigeon bridge for WebAuthn/passkey operations.
///
/// Platform implementations (iOS/macOS via ASAuthorizationController,
/// Android via CredentialManager) handle the native ceremony and return
/// JSON-serialized W3C WebAuthn Level 3 response objects.
class WebAuthnBridgeApi {
  /// Constructor for [WebAuthnBridgeApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WebAuthnBridgeApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Creates a new passkey credential on the device.
  ///
  /// [optionsJson] is a JSON-serialized `PublicKeyCredentialCreationOptions`.
  /// Returns a JSON-serialized `RegistrationResponseJSON`.
  Future<String> createCredential(String optionsJson) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.amplify_auth_cognito.WebAuthnBridgeApi.createCredential$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[optionsJson]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    !;
    return pigeonVar_replyValue as String;
  }

  /// Retrieves a passkey credential assertion for authentication.
  ///
  /// [optionsJson] is a JSON-serialized `PublicKeyCredentialRequestOptions`.
  /// Returns a JSON-serialized `AuthenticationResponseJSON`.
  Future<String> getCredential(String optionsJson) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.amplify_auth_cognito.WebAuthnBridgeApi.getCredential$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[optionsJson]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    !;
    return pigeonVar_replyValue as String;
  }

  /// Returns whether the current device/platform supports passkeys.
  Future<bool> isPasskeySupported() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.amplify_auth_cognito.WebAuthnBridgeApi.isPasskeySupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    !;
    return pigeonVar_replyValue as bool;
  }
}
